### ISSUE TITLE
Tags created with Tag Manager are not available in Typeahead

### ISSUE THREAD

**Issue by ghost** [drummerboy46/Umbraco-Tag-Manager#3]
I created some tags with Tag Manager:
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/3c081b7c-22e4-4169-845f-754cf46ca06e)

Then I set up 2 different property editors, Tag List and the original Tags:
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/2487da05-f39e-4007-99e1-fb9fd1a42e66)
The tag list displays all the tags created with Tag Manager, but when I type in the original Umbracos porperty editor, I don't get the any suggestions of existing tags. 

If I create a tag with the original property editor, I can see it in tag manager. If the name of the tag is the same, I can see two tags. After that the tags work in typeahead suggestion.

![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/a0009f4e-b029-49e5-9142-2d4071c3d678)
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/6d4c8007-f37d-4756-9993-efed972efc56)
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/4e574566-a237-41a2-94fe-2128f4c9aadb)

The only difference in the DB that I see is that language is missing:
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/ae8c8cb4-3a38-4fd9-bbe8-7ddfd6d6e186)

It looks like the default property editor is calling [TagsDataController](https://github.com/umbraco/Umbraco-CMS/blob/682b7656bc06534246b707e20794574afe3957f3/src/Umbraco.Web.BackOffice/PropertyEditors/TagsDataController.cs#L34) method `GetAllTags`, and that `_tagQuery` is not aware of the tags created with Tag Manager.

<img width="479" alt="image" src="https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/48cf9d13-2322-4f83-9dc5-f9c153de3839">

Is it just some cache invalidation issue or the typeahead does not see the tags created with tag manager?

**Comment by drummerboy46** [comment]
@gregor-tusar-sowa many thanks for your feedback.

Currently only the default language is supported. I should mention that in the docs, but its next on my list to fix! I assume from the s/s you defined a variant (DE)?

It'll be added to the next release.

**Comment by ghost** [comment]
I was looking a bit deeper and I also found that it does not fill the table cmsTagRelationship with that, it rather writes to the documents property. I think this is the reason that typeahead does not find the relavant tags. 
BTW, when is next release planned?

**Comment by drummerboy46** [comment]
Hmm, yes you're right its not in the relationship table only the tag table. I would've thought the Umbraco team considered this otherwise variants wont work properly with their own editor! Can you try it out?

I'll look to sort out variants this month.

**Comment by ghost** [comment]
I'll have a look in the evening. The quick look at the code of `TagManagerRepository.cs` I'm missing a `INSERT INTO cmsTagRelationship ...` code somewhere?

**Comment by drummerboy46** [comment]
If you're referring to my Repository its because its single language, when I update the project I've got to decide exactly how the "variant" is managed....

Separate trees?
Same tree?

The data for these would still only be defined in cmsTags though. I have separate content and media methods that then deal with any related content to them....This is the tricker bit once language variants come into play.

**Comment by ghost** [comment]
The default behaviour with Vary by culture on tags property editor:

German:
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/4c2ca33a-c7d2-49b5-b80a-47fdeb5354e3)

English:
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/431d24f7-4ce4-4c74-bad4-01718cdfd7db)
Typeahead does not suggest DE tags.

It suggest DE tags on other DE pages which is expected:
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/e42129c2-0c76-42db-a308-d12a754a2dbb)


The tags cannot actually be versioned by language, because there is no unique ID on them like nodeId.

**Comment by drummerboy46** [comment]
That looks like what I was expecting to see, many thanks for that. :-)

The way I see it is cmsTags defines the language and the tag, in the property editor it will pick only tags from cmsTags that are defined by the variant you are currently editing (languageId in cmsTags).

Does that sound correct to you?

**Comment by ghost** [comment]
Yes, `languageId` and `group`.

**Comment by drummerboy46** [comment]
@gregor-tusar-sowa a quick update on progress with the language variation changes.

The next version will contain the following...

1. Single (default) language tag editing functions as it did before with content and media
2. Variant & Invariant Tag editing, i.e. if language variance is set in the language settings, tags remain invariant. If language variance is set on the tag or tag list property full language variance is provided with tags.
3. In Tag Manager if multiple languages are detected you can create language variant tags and invariant tags. Each tag variant is shown in the tree as "tag name" - "language name".
4. Merge tags within a language variant/invariant
5. Fully tested on SQLite & MSSQL!
6. Fully tested on Umbraco 10, 12 & 13 with template projects added to the source code.

![Screenshot 2024-04-16 214720](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/6703035/e135c0a2-07ad-41a4-aa50-a0c66fa4d492)

![Screenshot 2024-04-16 214821](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/6703035/4be5e98d-785a-40e1-92e6-5261a6be65d5)

**Comment by drummerboy46** [comment]
@gregor-tusar-sowa version 13.1.0 has been released with language variant/invariant support & sqlite support.

**Comment by ghost** [comment]
Thanks for fixing this.
The built-in editor has a weird way how it gets tags, so the typeahead only works for tags that were already used on at least one of the content.
