### ISSUE TITLE
Package paths are wrong and cause 404 errors on Linux

### ISSUE THREAD

**Issue by ghost** [drummerboy46/Umbraco-Tag-Manager#4]
The paths in some TagManager files are wrong, which is causing file not found exception on linux systems (case sensitive paths). 

`package.manifest` [file](https://github.com/drummerboy46/Umbraco-Tag-Manager/blob/master/Umbraco%20Tag%20Manager/App_Plugins/TagManager/package.manifest)) have `tagManager` instead of `TagManager`. 
```
{
  "dashboards": [
    {
      "alias": "tagManager",
      "view": "~/App_Plugins/TagManager/backoffice/dashboards/dashboard.html",
      "sections": [ "TagManager" ]
    }
  ],
  "javascript": [
    "~/App_Plugins/TagManager/backoffice/scripts/tagManager.create.controller.js",
    "~/App_Plugins/TagManager/backoffice/scripts/tagManager.createGroup.controller.js",
    "~/App_Plugins/TagManager/backoffice/scripts/tagManager.delete.controller.js",
    "~/App_Plugins/TagManager/backoffice/scripts/tagManager.edit.controller.js",
    "~/App_Plugins/TagManager/backoffice/scripts/tagManager.group.controller.js",
    "~/App_Plugins/TagManager/backoffice/scripts/tagManager.dropdownFlexible.controller.js",
    "~/App_Plugins/TagManager/backoffice/scripts/tagManager.resource.js"
  ],
  "css": [
    "~/App_Plugins/TagManager/backoffice/css/tagManager.css"
  ]
}
```

`tagManager.edit.controller.js` [file](https://github.com/drummerboy46/Umbraco-Tag-Manager/blob/master/Umbraco%20Tag%20Manager/App_Plugins/TagManager/backoffice/scripts/tagManager.edit.controller.js) has wrong path to view:
```
...94...
        $scope.cmsTags = {
            tag: "",
            languageId: null,
            group: "",
            alias: "mergeTags",
            label: "Select Tag",
            description: "The selected tag will be merged and will inherit this tags associations with content and media.",
            config: {
                multiple: false,
            },
            mergeTag: [],
            view: "/App_Plugins/TagManager/backoffice/propertyEditor/dropdownFlexible.html"
        };
...108...
```

Could you please fix it?

**Comment by drummerboy46** [comment]
@gregor-tusar-sowa - would this be something you can test for me as I've never worked with linux envs. I'll fix it up for the next release.

**Comment by ghost** [comment]
Sure, when could you make a new release? I wanted to make a PR, but I couldn't .

**Comment by drummerboy46** [comment]
@gregor-tusar-sowa I've created a branch v13-dev can you create a PR on that branch?

**Comment by ghost** [comment]
I created now a PR:
https://github.com/drummerboy46/Umbraco-Tag-Manager/pull/5

**Comment by drummerboy46** [comment]
@gregor-tusar-sowa all merged and new package released.
